export const ATTRS = {
    PAGE: 'data-tables-page',
    ROOT: 'data-tables-root',
    SEARCH_FORM: 'data-tables-search-form',
    FILTER_BAR: 'data-tables-filter-bar',
    SAVED_VIEWS: 'data-tables-saved-views',
    SUMMARY: 'data-tables-summary',
    SUBTITLE: 'data-tables-subtitle',
    TOTAL: 'data-tables-total',

    ROW: 'data-tables-row',
    ROW_ID: 'data-tables-row-id',
    ROW_CHECKBOX: 'data-tables-row-checkbox',
    SELECT_ALL: 'data-tables-select-all',
    CELL_EDIT: 'data-tables-cell-edit',
    CELL_EDIT_TEMPLATE: 'data-tables-cell-edit-template',
    CELL_EDIT_INPUT: 'data-tables-cell-edit-input',
    CELL_EDIT_FORM: 'data-tables-cell-edit-form',
    CELL_EDIT_ERROR: 'data-tables-cell-edit-error',
    CELL_EDIT_SAVE: 'data-tables-cell-edit-save',
    CELL_EDIT_CANCEL: 'data-tables-cell-edit-cancel',

    CHIP: 'data-tables-chip',
    CHIP_REMOVE: 'data-tables-chip-remove',
    FILTER_APPLY: 'data-tables-filter-apply',
    FILTER_CLEAR: 'data-tables-filter-clear',
    FILTER_GROUP: 'data-tables-filter-group',
    FILTER_BAR_GROUPED: 'data-tables-filter-bar-grouped',
    FILTER_POPOVER_FORM: 'data-tables-filter-popover-form',
    FILTER_POPOVER_VALUE: 'data-tables-filter-popover-value',

    BULK_SCOPE: 'data-tables-bulk-scope',
    BULK_FORM: 'data-tables-bulk-form',
    BULK_ACTION: 'data-tables-bulk-action',
    BULK_ACTION_BODY: 'data-tables-bulk-action-body',
    BULK_ACTION_SUBMIT: 'data-tables-bulk-action-submit',
    BULK_ACTION_INPUT: 'data-tables-bulk-action-input',
    BULK_ACTION_ERROR: 'data-tables-bulk-action-error',
    BULK_ACTION_FORM_BUTTON: 'data-tables-bulk-action-form-button',
    BULK_CONFIRM: 'data-tables-bulk-confirm',
    BULK_QUEUED: 'data-tables-bulk-queued',
    BULK_CLEAR: 'data-tables-bulk-clear',
    BULK_COUNT: 'data-tables-bulk-count',
    BULK_IDS_INPUT: 'data-tables-bulk-ids-input',
    BULK_PREVIEW_URL: 'data-tables-bulk-preview-url',
    LOADING_TEXT: 'data-tables-loading-text',

    ROW_ACTION_BODY: 'data-tables-row-action-body',
    ROW_ACTION_ERROR: 'data-tables-row-action-error',
    ROW_ACTION_SUBMIT: 'data-tables-row-action-submit',
    ROW_ACTION_FORM_BUTTON: 'data-tables-row-action-form-button',
    ROW_ACTION_CONFIRM: 'data-tables-row-action-confirm',
    ROW_PREVIEW_URL: 'data-tables-row-preview-url',
    CONFIRM_PREVIEW_BODY: 'data-tables-confirm-preview-body',
    CONFIRM_PREVIEW_SUBMIT: 'data-tables-confirm-preview-submit',

    SAVED_VIEW: 'data-tables-saved-view',
    SAVED_VIEW_KEY: 'data-tables-saved-view-key',
    SAVE_VIEW_FORM: 'data-tables-save-view-form',
    SAVE_VIEW_TRIGGER: 'data-tables-save-view-trigger',
    SAVE_VIEW_STATE: 'data-tables-save-view-state',
    SAVE_VIEW_ERROR: 'data-tables-save-view-error',
    USER_VIEW_ID: 'data-tables-user-view-id',
    USER_VIEW_DELETE: 'data-tables-user-view-delete',
    PREFS_FORM: 'data-tables-prefs-form',
    PREFS_TRIGGER: 'data-tables-prefs-trigger',
    PREFS_SUBMIT: 'data-tables-prefs-submit',
    PREFS_RESET: 'data-tables-prefs-reset',
    PREFS_CANCEL: 'data-tables-prefs-cancel',
    PREFS_ERROR: 'data-tables-prefs-error',

    QB_ROOT: 'data-tables-qb-root',
    QB_STATE: 'data-tables-qb-state',
    QB_SCHEMA: 'data-tables-qb-schema',
    QB_GROUP: 'data-tables-qb-group',
    QB_COND: 'data-tables-qb-cond',
    QB_CLEAR: 'data-tables-qb-clear',
    QB_RESET: 'data-tables-qb-reset',
    QB_APPLY: 'data-tables-qb-apply',

    SHARED_TEMPLATE: 'data-tables-shared-template',

    AUTOCOMPLETE: 'data-tables-autocomplete',
    AUTOCOMPLETE_INPUT: 'data-tables-autocomplete-input',
    AUTOCOMPLETE_RESULTS: 'data-tables-autocomplete-results',
    AUTOCOMPLETE_SELECTED_LIST: 'data-tables-autocomplete-selected-list',
    AUTOCOMPLETE_MULTIPLE: 'data-tables-autocomplete-multiple',
    AUTOCOMPLETE_URL: 'data-tables-autocomplete-url',
    AUTOCOMPLETE_FIELD: 'data-tables-autocomplete-field',
    AUTOCOMPLETE_DEBOUNCE: 'data-tables-autocomplete-debounce',
    AUTOCOMPLETE_MIN_CHARS: 'data-tables-autocomplete-min-chars',
    AUTOCOMPLETE_CHIP_REMOVE: 'data-tables-autocomplete-chip-remove',

    PROGRESS_TRAY: 'data-tables-progress-tray',
    PROGRESS_TOASTS: 'data-tables-progress-toasts',
    PROGRESS_CARD: 'data-tables-progress-card',
    PROGRESS_FILL: 'data-tables-progress-fill',
    PROGRESS_COUNTER: 'data-tables-progress-counter',
    PROGRESS_DISMISS: 'data-tables-progress-dismiss',

    ACTION_LOG: 'data-tables-action-log',
    ACTION_LOG_BODY: 'data-tables-action-log-body',
    ACTION_LOG_UNDO: 'data-tables-action-log-undo',
    ACTION_LOG_URL: 'data-tables-action-log-url',
    ACTION_LOG_TRIGGER: 'data-tables-action-log-trigger',
    EXPORT: 'data-tables-export',
};

export const EVENTS = {
    RENDERED: 'tables:rendered',
    NAVIGATE: 'tables:navigate',
    TOTAL_CHANGED: 'tables:total-changed',
    FLASH: 'tables:flash',
};

export function sel(name, value) {
    if (value === undefined) return `[${name}]`;
    return `[${name}="${String(value).replace(/"/g, '\\"')}"]`;
}
